[prompt]
scan_timeout = 10
add_newline = false

[character]
error_symbol = "[❯](bold red)"
success_symbol = "[❯](bold green)"

[directory]
truncation_length = 100
truncate_to_repo = false
truncation_symbol = "…/"

[aws]
format = 'on [$sybol($profile )(\($region\) )]($style)'
style = 'bold blue'

[battery]
disabled = true


